### ISSUE TITLE
Adding this repo to the Tree-sitter docs

### ISSUE THREAD

**Issue by maxbrunsfeld** [Azganoth/tree-sitter-lua#1]
Really nice work on this parser; thanks for creating it!

I'm just opening this issue as a heads up that I'm adding a link to this repository in the [Tree-sitter docs](https://tree-sitter.github.io). If for any reason you'd prefer that I *not* have this link, I'll take it down.

**Comment by Azganoth** [comment]
That's okay, thanks for the compliment!
