### ISSUE TITLE
Lua Syntax highlighting breaks, if there is a single quote (') in the comment line.

### ISSUE THREAD

**Issue by yssource** [Azganoth/tree-sitter-lua#14]
``` lua
function hello()
end

-- test with single quote ' ine comment line

function world()
end
```

![Screenshot_2022-06-21_18-18-04](https://user-images.githubusercontent.com/3756334/174776865-5b052bf0-12a2-4264-a30c-ccc5d3d1a697.png)

**Comment by Azganoth** [comment]
Are you sure this package is being used for that highlighting? If yes, what version?

Highlighting your code with the latest version gives the expected result:
![Captura de tela 2022-06-21 183138](https://user-images.githubusercontent.com/24205667/174900815-640b8a8c-7f98-46f3-87a8-59e75bcbc11b.png)

**Comment by yssource** [comment]
I'm looking into it.
Indeed, it is not caused by tree-sitter-lua.
I use emacs lsp, and it maybe come from that.
Thanks a lot.
