### ISSUE TITLE
Multiple concurrent Lua parsers can conflict from global variables in scanner

### ISSUE THREAD

**Issue by logancollins** [Azganoth/tree-sitter-lua#15]
There appears to be an issue with the lexical scanner (in `scanner.c`) when used from an application that:

1. Compiles the grammar to native code from C
2. Runs multiple concurrent parsers

Due to the scanner's use of global variables (`started` and `depth`), multiple parsers can overwrite each others' variable state, leading to incorrect parsing.

I think the best option would be to move those two variables into the `payload` pointer that can be allocated when the scanner is created.

I have a pull request with some tweaks ready, and will be opening it soon!

**Comment by Azganoth** [comment]
Nice catch! Using `payload` to hold the parser's state seems to be the logical solution.
