### ISSUE TITLE
Prebuild binaries for Atom 1.40 missing

### ISSUE THREAD

**Issue by iTob191** [Azganoth/tree-sitter-lua#3]
Installing `language-lua-plus` (1.6.0) in Atom 1.40 fails because of missing prebuild binaries.

**Comment by Azganoth** [comment]
I've uploaded all available binaries because I don't know what binaries are missing, if you still can't install it, please, give me more info.

**Comment by iTob191** [comment]
It works with those new binaries, thanks!
