### ISSUE TITLE
version 12

### ISSUE THREAD

**Issue by codediy** [Azganoth/tree-sitter-lua#9]
tree-sitter ver13。lua ver12。build fail

**Comment by cetfor** [comment]
I'm also experiencing this issue:
`ValueError: Incompatible Language version 12. Must be between 13 and 13`

The version is defined in src/parser.c as `#define LANGUAGE_VERSION 12`.  Changing this to `#define LANGUAGE_VERSION 13` and rebuilding works fine - at least for the Lua scripts I've parsed with it.

I realize this is stupid, and I quite honestly have no idea what ramifications this has. 

Searching the `tree-sitter` repo I came across `ts_language_version` which sheds some light on the use of `LANGUAGE_VERSION`:

"Get the ABI version number for this language. This version number is used to ensure that languages were generated by a compatible version of Tree-sitter."

Ah cool.  Well, I still think blindly changing the `LANGUAGE_VERSION` to 13 and YOLO re-compiling is dumb, but I mean, it seems to work?

At any rate, if anyone can explain the process that typically goes into updating languages and testing them the correct way, I'd be very appreciative.

**Comment by shrivastavadisha** [comment]
I am also facing the same problem. Changing the language version didn't help. Can someone suggest a fix for this?

**Comment by Qix-** [comment]
Nah don't do that, just re-build it. You can use my fork if you don't need any of the fancy Node stuff and just the parser bits (or even if you do, idk, maybe they still work as you'd expect).

https://github.com/qix-/tree-sitter-lua

**Comment by Azganoth** [comment]
Fixed in [v2.0.0](/Azganoth/tree-sitter-lua/releases/tag/v2.0.0).
